import CustomDomain from '../models/customDomainModel.js';

/* =========================================================
   CREATE CUSTOM DOMAIN / ASSIGNMENT
   ========================================================= */
export const createCustomDomain = async (req, res) => {
  try {
    const {
      userId,
      name,
      userPrompt,
      mainTopic,
      courses,
      description,
      isAssignment,
      questionLimit,
    } = req.body;

    if (!userId || !name || !userPrompt) {
      return res.status(400).json({
        status: 'error',
        message: 'Missing required fields: userId, name, userPrompt',
      });
    }

    /* ---------------- AI MOCK (Replace Later) ---------------- */
    const totalQuestions = questionLimit || 15;

    const generatedQuestions = isAssignment
      ? Array.from({ length: totalQuestions }, (_, i) => ({
          questionText: `Question ${i + 1} about ${name}`,
          options: ['Option A', 'Option B', 'Option C', 'Option D'],
          correctIndex: Math.floor(Math.random() * 4),
          explanation: 'This explanation is generated by AI.',
          difficulty: Math.ceil(Math.random() * 5),
        }))
      : [];

    /* ---------------- Create Document ---------------- */
    const customDomain = new CustomDomain({
      userId,
      name,
      userPrompt,
      mainTopic: mainTopic || name,
      description: description || '',
      courses: courses || [],
      isAssignment: isAssignment || false,

      // Assignment-specific
      questionLimit: totalQuestions,
      questions: generatedQuestions,

      // UI / Meta
      icon: 'Sparkles',
      color: 'hsl(48, 96%, 53%)',
      difficulty: 3,
      progress: 0,
      isCustom: true,
    });

    const savedDomain = await customDomain.save();

    return res.status(201).json({
      status: 'success',
      message: isAssignment
        ? 'Assignment created successfully'
        : 'Custom domain created successfully',
      data: savedDomain,
    });
  } catch (error) {
    console.error('Error creating custom domain:', error);
    return res.status(500).json({
      status: 'error',
      message: 'Internal server error',
      error: error.message,
    });
  }
};

/* =========================================================
   GET ALL CUSTOM DOMAINS FOR A USER
   ========================================================= */
export const getUserCustomDomains = async (req, res) => {
  try {
    const { userId } = req.params;

    const customDomains = await CustomDomain.find({ userId })
      .sort({ createdAt: -1 });

    return res.status(200).json({
      status: 'success',
      data: customDomains,
    });
  } catch (error) {
    return res.status(500).json({
      status: 'error',
      message: 'Internal server error',
    });
  }
};

/* =========================================================
   GET SINGLE CUSTOM DOMAIN / ASSIGNMENT
   ========================================================= */
export const getCustomDomainById = async (req, res) => {
  try {
    const customDomain = await CustomDomain.findById(req.params.id);

    if (!customDomain) {
      return res.status(404).json({
        status: 'error',
        message: 'Custom domain not found',
      });
    }

    return res.status(200).json({
      status: 'success',
      data: customDomain,
    });
  } catch (error) {
    return res.status(500).json({
      status: 'error',
      message: 'Internal server error',
    });
  }
};

/* =========================================================
   UPDATE CUSTOM DOMAIN / ASSIGNMENT
   ========================================================= */
export const updateCustomDomain = async (req, res) => {
  try {
    const updated = await CustomDomain.findByIdAndUpdate(
      req.params.id,
      req.body,
      { new: true }
    );

    return res.status(200).json({
      status: 'success',
      data: updated,
    });
  } catch (error) {
    return res.status(500).json({
      status: 'error',
      message: 'Internal server error',
    });
  }
};

/* =========================================================
   DELETE CUSTOM DOMAIN / ASSIGNMENT
   ========================================================= */
export const deleteCustomDomain = async (req, res) => {
  try {
    await CustomDomain.findByIdAndDelete(req.params.id);

    return res.status(200).json({
      status: 'success',
      message: 'Deleted successfully',
    });
  } catch (error) {
    return res.status(500).json({
      status: 'error',
      message: 'Internal server error',
    });
  }
};
